### PR TITLE
Upgrade 0.86.0

### PR DESCRIPTION
**Pull request by wlewis-formative**
❓ Is there a better way to arrange (not quite the right word, but...) these commits using `git`? There were only two small conflicts after merging the upstream master branch, but it's difficult to see that that was the case here.

### CODE REVIEW

**Comment by dobesv** [comment]
> Is there a better way to arrange (not quite the right word, but...) these commits using git?

I think probably should have merged master with upstream first, then create the PR

**Comment by dobesv** [comment]
I sort of ... "force rebased" this on the upstream master, can you take one last look and see if I accidentally undid anything?

**Comment by wlewis-formative** [comment]
> I think probably should have merged master with upstream first, then create the PR

Ah, that makes sense.

**Comment by wlewis-formative** [comment]
And your "force rebase" changes look good to me 👍 Thanks for doing that.

**Pull request merged**
